#!/usr/bin/env python3
"""Story-content completeness: every major Project Blonde story line must be on the road, or be a listed gap.

    python3 tools/qa_story.py [--game ../blonde]      -> exit 1 on any failure; writes STORY-COVERAGE.md

Reads content/storylines.json (the registry) and checks, for each story marked covered:
  - its chapter is on the road (content/chapters.json) and has every registered stage as a step;
  - the built page exists and is linked from the road page and from at least one other chapter (run build.py first);
and, when the game folder is present (it is not on the Pages runner):
  - every registered script symbol is still in the linked build's symbol table;
  - no new family of story scripts has appeared that is neither a registered story nor a listed engine family.
"""
import argparse, collections, json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
J = lambda p: json.loads(Path(p).read_text(encoding="utf-8"))
MIN_FAMILY = 6          # a prefix with this many *_Text_* symbols counts as a script family


def main():
    ap = argparse.ArgumentParser(); ap.add_argument("--game", default=str(ROOT.parent / "blonde"))
    game = Path(ap.parse_args().game)
    reg = J(ROOT / "content/storylines.json")
    order = J(ROOT / "content/chapters.json")["regions"]
    road = {f'{r["id"]}/{s}' for r in order for s in r["chapters"]}
    chapters = {f'{c["region"]}/{c["slug"]}': c for f in (ROOT / "content/walkthrough").glob("*.json") for c in J(f)["chapters"]}
    url = lambda k: (f'postgame/{k.split("/")[1]}' if k.startswith("postgame/") else f"walkthrough/{k}")
    dist = ROOT / "dist"
    bad, rows = [], []
    road_html = (dist / "walkthrough/index.html").read_text(encoding="utf-8") if (dist / "walkthrough/index.html").exists() else None
    if road_html is None:
        bad.append("dist/ is missing: run tools/build.py first")
    pages = {k: (dist / url(k) / "index.html") for k in road}
    html = {k: p.read_text(encoding="utf-8") for k, p in pages.items() if p.exists()}

    for s in reg["storylines"]:
        k = s.get("chapter")
        if s["status"] == "covered":
            if k not in road or k not in chapters:
                bad.append(f'{s["id"]}: chapter {k} is not on the road'); continue
            have = {st["id"] for st in chapters[k]["steps"]}
            for st in s.get("stages", []):
                if st not in have:
                    bad.append(f'{s["id"]}: stage "{st}" is missing from {k}')
            if road_html is not None:
                href = f'/{url(k)}/"'
                if k not in html:
                    bad.append(f'{s["id"]}: page for {k} was not built')
                elif href not in road_html:
                    bad.append(f'{s["id"]}: {k} is not linked from the road page')
                elif not any(href in h for o, h in html.items() if o != k):
                    bad.append(f'{s["id"]}: {k} is not linked from any other chapter')
        elif s["status"] != "gap":
            bad.append(f'{s["id"]}: unknown status {s["status"]}')
        rows.append(s)

    sym_note = "Game folder not present: script symbols were not checked on this run."
    symfile = None
    if game.exists():
        sys.path.insert(0, str(ROOT / "tools"))
        import romx
        symfile = game / romx.BUILD["symbols"]
    if symfile and symfile.exists():
        S = J(symfile)
        for s in reg["storylines"]:
            for name in s.get("symbols", []):
                if name not in S:
                    bad.append(f'{s["id"]}: script {name} is no longer in the game (story changed or removed)')
        fam = collections.Counter(m[1] for n in S for m in [re.match(r"^([A-Za-z0-9]+)_Text_", n)] if m)
        maps = {m.replace("_hns", "").split("_")[0] for m in J(ROOT / "data/rom/world.json")}
        known = set(reg["engine_families"]["names"]) | {s["family"] for s in reg["storylines"] if s.get("family")}
        new = sorted(p for p, n in fam.items() if n >= MIN_FAMILY and p not in maps and p not in known)
        for p in new:
            bad.append(f'new script family "{p}" ({fam[p]} text entries) is not a registered story line: add it to content/storylines.json')
        sym_note = f'Script symbols checked against {romx.BUILD["version"]} ({symfile.name}): {sum(len(s.get("symbols", [])) for s in reg["storylines"])} symbols, {len(known)} known script families, {len(new)} new.'

    L = ["# Story coverage", "", "_Generated by `tools/qa_story.py` from `content/storylines.json`. Edit the registry, not this file._", "",
         "| Story line | Kind | Status | Chapter | Evidence | Note |", "|---|---|---|---|---|---|"]
    for s in rows:
        k = s.get("chapter")
        L.append(f'| {s["title"]} | {s["kind"]} | {"covered" if s["status"] == "covered" else "**gap**"} | {("`/" + url(k) + "/`") if k else "none"} | {s.get("evidence", "")} | {s.get("note", "")} |')
    L += ["", sym_note, "", f'Result: {"FAIL" if bad else "PASS"} ({sum(1 for s in rows if s["status"] == "covered")} covered, {sum(1 for s in rows if s["status"] == "gap")} known gaps).', ""]
    L += [f"- FAIL: {b}" for b in bad]
    (ROOT / "STORY-COVERAGE.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print(json.dumps({"covered": sum(1 for s in rows if s["status"] == "covered"), "gaps": [s["id"] for s in rows if s["status"] == "gap"], "failures": len(bad), "symbols": sym_note}, ensure_ascii=False))
    for b in bad:
        print("  FAIL", b)
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
